# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83d5b55d326fcab7a6087d2f9dec114843103f474e3c25640da1c4b0f9193f448f489a29f4b0483a14ed22c2249ef1d9657c60a5841dee0ff85f8d8d26bac977

test:
  secret_key_base: 24a399071b02eb275a425153d7439971d73178e85a1df38326eef68ee81cb42cf85c2757d9b5d5c68f0b4b13ac8c23c0f7961bb44f2d2b8fc8dea8a8ac956132

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
